# Generated by Django 5.1.1 on 2024-10-01 03:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('phone', models.CharField(max_length=14)),
                ('telegram_id', models.CharField(max_length=127)),
                ('national_id', models.CharField(max_length=127)),
                ('affiliation', models.CharField(max_length=127)),
                ('major', models.CharField(max_length=127)),
                ('prof_name', models.CharField(max_length=63)),
                ('prof_email', models.EmailField(max_length=127)),
                ('resume', models.FileField(upload_to='resumes')),
                ('resume_share_consent', models.PositiveSmallIntegerField(choices=[(1, 'Share'), (2, 'Do not Share')], default=1)),
                ('league', models.PositiveSmallIntegerField(choices=[(1, 'Undergrad'), (2, 'Grad')], default=1)),
                ('exceeded_time', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('judge1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge1', to='authenticator.judge')),
                ('judge2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge2', to='authenticator.judge')),
                ('judge3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge3', to='authenticator.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('comment', models.CharField(blank=True, max_length=511, null=True)),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.judge')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticator.contestant')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
